name: CI

on:
  pull_request:
    branches: [ "release/**", "hotfix/**" ]
  push:
    branches: [ "release/**", "hotfix/**" ]

jobs:
  build: 
    uses: ./.github/workflows/nodejs-build.yml
  merge-in-dev:
    if: ${{ github.ref_name != 'dev' && github.event_name == 'push' }}
    name: 'pull in dev branch'
    needs: build
    permissions:
      pull-requests: write
    uses: ./.github/workflows/step-merge-in-dev.yml
    secrets: inherit
